// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> Any
}

public enum ErrorResponse : Error {
    case Error(Int, Data?, Error)
}

open class Response<T> {
    open let statusCode: Int
    open let header: [String: String]
    open let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: HTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = Int()
class Decoders {
    static fileprivate var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()

    static func addDecoder<T>(clazz: T.Type, decoder: @escaping ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as AnyObject }
    }

    static func decode<T>(clazz: T.Type, discriminator: String, source: AnyObject) -> T {
        let key = discriminator;
        if let decoder = decoders[key] {
            return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decode<T>(clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }

    static func decode<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }

    static func decode<T>(clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.int32Value as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.int64Value as! T;
        }
        if T.self is UUID.Type && source is String {
            return UUID(uuidString: source as! String) as! T
        }
        if source is T {
            return source as! T
        }
        if T.self is Data.Type && source is String {
            return Data(base64Encoded: source as! String) as! T
        }

        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    private static var __once: () = {
        let formatters = [
            "yyyy-MM-dd",
            "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
            "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd'T'HH:mm:ss.SSS"
        ].map { (format: String) -> DateFormatter in
            let formatter = DateFormatter()
            formatter.dateFormat = format
            return formatter
        }
        // Decoder for Date
        Decoders.addDecoder(clazz: Date.self) { (source: AnyObject) -> Date in
           if let sourceString = source as? String {
                for formatter in formatters {
                    if let date = formatter.date(from: sourceString) {
                        return date
                    }
                }
            }
            if let sourceInt = source as? Int {
                // treat as a java date
                return Date(timeIntervalSince1970: Double(sourceInt / 1000) )
            }
            fatalError("formatter failed to parse \(source)")
        } 

        // Decoder for [FindUserResponse]
        Decoders.addDecoder(clazz: [FindUserResponse].self) { (source: AnyObject) -> [FindUserResponse] in
            return Decoders.decode(clazz: [FindUserResponse].self, source: source)
        }
        // Decoder for FindUserResponse
        Decoders.addDecoder(clazz: FindUserResponse.self) { (source: AnyObject) -> FindUserResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = FindUserResponse()
            instance.success = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["success"] as AnyObject?)
            instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"] as AnyObject?)
            instance.users = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["users"] as AnyObject?)
            return instance
        }


        // Decoder for [GeneralResponse]
        Decoders.addDecoder(clazz: [GeneralResponse].self) { (source: AnyObject) -> [GeneralResponse] in
            return Decoders.decode(clazz: [GeneralResponse].self, source: source)
        }
        // Decoder for GeneralResponse
        Decoders.addDecoder(clazz: GeneralResponse.self) { (source: AnyObject) -> GeneralResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = GeneralResponse()
            instance.success = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["success"] as AnyObject?)
            instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"] as AnyObject?)
            return instance
        }


        // Decoder for [ListFriendResponse]
        Decoders.addDecoder(clazz: [ListFriendResponse].self) { (source: AnyObject) -> [ListFriendResponse] in
            return Decoders.decode(clazz: [ListFriendResponse].self, source: source)
        }
        // Decoder for ListFriendResponse
        Decoders.addDecoder(clazz: ListFriendResponse.self) { (source: AnyObject) -> ListFriendResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = ListFriendResponse()
            instance.success = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["success"] as AnyObject?)
            instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"] as AnyObject?)
            instance.friends = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["friends"] as AnyObject?)
            return instance
        }


        // Decoder for [ListFriendResponseFriends]
        Decoders.addDecoder(clazz: [ListFriendResponseFriends].self) { (source: AnyObject) -> [ListFriendResponseFriends] in
            return Decoders.decode(clazz: [ListFriendResponseFriends].self, source: source)
        }
        // Decoder for ListFriendResponseFriends
        Decoders.addDecoder(clazz: ListFriendResponseFriends.self) { (source: AnyObject) -> ListFriendResponseFriends in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = ListFriendResponseFriends()
            instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"] as AnyObject?)
            instance.presence = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["presence"] as AnyObject?)
            return instance
        }


        // Decoder for [LoginResponse]
        Decoders.addDecoder(clazz: [LoginResponse].self) { (source: AnyObject) -> [LoginResponse] in
            return Decoders.decode(clazz: [LoginResponse].self, source: source)
        }
        // Decoder for LoginResponse
        Decoders.addDecoder(clazz: LoginResponse.self) { (source: AnyObject) -> LoginResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = LoginResponse()
            instance.success = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["success"] as AnyObject?)
            instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"] as AnyObject?)
            instance.token = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["token"] as AnyObject?)
            return instance
        }


        // Decoder for [OnlineClientListResponse]
        Decoders.addDecoder(clazz: [OnlineClientListResponse].self) { (source: AnyObject) -> [OnlineClientListResponse] in
            return Decoders.decode(clazz: [OnlineClientListResponse].self, source: source)
        }
        // Decoder for OnlineClientListResponse
        Decoders.addDecoder(clazz: OnlineClientListResponse.self) { (source: AnyObject) -> OnlineClientListResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = OnlineClientListResponse()
            instance.success = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["success"] as AnyObject?)
            instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"] as AnyObject?)
            instance.clients = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["clients"] as AnyObject?)
            return instance
        }


        // Decoder for [UserTopicListResponse]
        Decoders.addDecoder(clazz: [UserTopicListResponse].self) { (source: AnyObject) -> [UserTopicListResponse] in
            return Decoders.decode(clazz: [UserTopicListResponse].self, source: source)
        }
        // Decoder for UserTopicListResponse
        Decoders.addDecoder(clazz: UserTopicListResponse.self) { (source: AnyObject) -> UserTopicListResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = UserTopicListResponse()
            instance.success = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["success"] as AnyObject?)
            instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"] as AnyObject?)
            instance.topics = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["topics"] as AnyObject?)
            return instance
        }
    }()

    static fileprivate func initialize() {
        _ = Decoders.__once
    }
}
