# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatMQTT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'AlamofireDomain', '~> 4.0'
	pod 'CocoaMQTT' 
	pod 'SwiftyJSON'
    	pod 'SegueKit', '~> 3.0.0-beta.2'
 	pod 'SVProgressHUD'
  	pod 'TaskQueue'
	pod 'ISEmojiView'

  # Pods for ChatMQTT

  target 'ChatMQTTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatMQTTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
